# docker-compose.yml
services:
  web:
    image: githubyumao/mcsmanager-web:latest
    ports:
      - "23333:23333"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/user/appdata/mcsm/web/data:/opt/mcsmanager/web/data
      - /mnt/user/appdata/mcsm/web/logs:/opt/mcsmanager/web/logs

  daemon:
    image: githubyumao/mcsmanager-daemon:latest
    restart: unless-stopped
    ports:
      - "24444:24444"
    environment:
      - MCSM_DOCKER_WORKSPACE_PATH=/mnt/user/appdata/mcsm/daemon/data/InstanceData
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/user/appdata/mcsm/daemon/data:/opt/mcsmanager/daemon/data
      - /mnt/user/appdata/mcsm/daemon/logs:/opt/mcsmanager/daemon/logs
      - /var/run/docker.sock:/var/run/docker.sock